### ISSUE TITLE
Unity & Cinnamon colors

### ISSUE THREAD

**Issue by jpnurmi** [ubuntu/yaru_colors.dart#8]
_Originally posted by @ItzSwirlz in https://github.com/ubuntu/yaru_colors.dart/issues/5#issuecomment-1309056509_:

> We also should add Unity (at least) and possibly Cinnamon

**Comment by jpnurmi** [comment]
Hey @ItzSwirlz, what are the primary or accent color values for these?

**Comment by jpnurmi** [comment]
The color(s) need to be added here: https://github.com/ubuntu/yaru_colors.dart/blob/main/lib/src/colors.dart#L129-L170

**Comment by JPeisach** [comment]
The Cinnamon color is basically pulled from the cinnamon Desktop logo. #DD682A

**Comment by jpnurmi** [comment]
Oops, reopened because we're still missing Unity.

**Comment by jpnurmi** [comment]
- https://github.com/ubuntu/yaru.dart/pull/279
